#!/bin/bash

t=1
header="======= Pomodoro Timer ======"
cycle=1

while [ $t -eq 1 ]; do 

   for m in {0..24}; do 
       for s in {0..59}; do
            printf "%s\n" "$header"
            printf "%10s" "Time to work: "
            printf "%02d:%02d\n" $m $s
            sleep 1s
            clear
        done
    done
   clear
    
    cycle=$((++cycle))

    if [ $cycle -lt 4 ]; then

        for m in {0..5}; do 
            for s in {0..59}; do
                printf "%s\n" "$header"
                printf "%10s" "Time to rest "
                printf "%02d:%02d\n" $m $s
                sleep 1s
                clear
            done
        done
        clear

    else

        for m in {0..19}; do 
            for s in {0..59}; do
                printf "%s\n" "$header"
                printf "%10s" "Time to get up for a coffee"
                printf "%02d:%02d\n" $m $s
                sleep 1s
                clear
            done
        done
        clear
    fi
done
